# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vector.proto',
  package='Messages',
  syntax='proto3',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n\x0cvector.proto\x12\x08Messages\"0\n\x08Revision\x12\x11\n\tmajor_rev\x18\x01 \x01(\x03\x12\x11\n\tminor_rev\x18\x02 \x01(\x03\"I\n\x07\x45xtrema\x12\x0c\n\x04\x64ims\x18\x01 \x01(\x05\x12\x0f\n\x03min\x18\x02 \x03(\x01\x42\x02\x10\x01\x12\x0f\n\x03max\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x0e\n\x06is_set\x18\x04 \x01(\x08\"\x8a\x01\n\x08Vector32\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ncomponents\x18\x02 \x01(\x05\x12\x13\n\x0binterleaved\x18\x03 \x01(\x08\x12$\n\x08revision\x18\x04 \x01(\x0b\x32\x12.Messages.Revision\x12\r\n\x05units\x18\x05 \x01(\t\x12\x12\n\x06values\x18\n \x03(\x02\x42\x02\x10\x01\"\x8a\x01\n\x08Vector64\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ncomponents\x18\x02 \x01(\x05\x12\x13\n\x0binterleaved\x18\x03 \x01(\x08\x12$\n\x08revision\x18\x04 \x01(\x0b\x32\x12.Messages.Revision\x12\r\n\x05units\x18\x05 \x01(\t\x12\x12\n\x06values\x18\n \x03(\x01\x42\x02\x10\x01\"+\n\x07Indices\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x06values\x18\x02 \x03(\x05\x42\x02\x10\x01\"\xa5\x02\n\x08\x45lements\x12\x13\n\x07indices\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x07strides\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x07offsets\x18\x03 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05types\x18\x04 \x03(\x05\x42\x02\x10\x01\x12\x0f\n\x03ids\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x16\n\nid_offsets\x18\x06 \x03(\x05\x42\x02\x10\x01\x12 \n\x14num_elements_with_id\x18\x07 \x03(\x05\x42\x02\x10\x01\x12\x17\n\x0bid_to_index\x18\x08 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05\x66lags\x18\t \x03(\x05\x42\x02\x10\x01\x12\x13\n\x07\x63\x65nters\x18\n \x03(\x01\x42\x02\x10\x01\x12\x13\n\x07lengths\x18\x0b \x03(\x01\x42\x02\x10\x01\x12\x11\n\x05\x61reas\x18\x0c \x03(\x01\x42\x02\x10\x01\x12\x13\n\x07volumes\x18\r \x03(\x01\x42\x02\x10\x01\x42\x03\xf8\x01\x01\x62\x06proto3')
)




_REVISION = _descriptor.Descriptor(
  name='Revision',
  full_name='Messages.Revision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major_rev', full_name='Messages.Revision.major_rev', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor_rev', full_name='Messages.Revision.minor_rev', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=74,
)


_EXTREMA = _descriptor.Descriptor(
  name='Extrema',
  full_name='Messages.Extrema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dims', full_name='Messages.Extrema.dims', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='Messages.Extrema.min', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='Messages.Extrema.max', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_set', full_name='Messages.Extrema.is_set', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=149,
)


_VECTOR32 = _descriptor.Descriptor(
  name='Vector32',
  full_name='Messages.Vector32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Messages.Vector32.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='components', full_name='Messages.Vector32.components', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interleaved', full_name='Messages.Vector32.interleaved', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='Messages.Vector32.revision', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='units', full_name='Messages.Vector32.units', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='Messages.Vector32.values', index=5,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=290,
)


_VECTOR64 = _descriptor.Descriptor(
  name='Vector64',
  full_name='Messages.Vector64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Messages.Vector64.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='components', full_name='Messages.Vector64.components', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interleaved', full_name='Messages.Vector64.interleaved', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='Messages.Vector64.revision', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='units', full_name='Messages.Vector64.units', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='Messages.Vector64.values', index=5,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=431,
)


_INDICES = _descriptor.Descriptor(
  name='Indices',
  full_name='Messages.Indices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Messages.Indices.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='Messages.Indices.values', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=476,
)


_ELEMENTS = _descriptor.Descriptor(
  name='Elements',
  full_name='Messages.Elements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='indices', full_name='Messages.Elements.indices', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strides', full_name='Messages.Elements.strides', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offsets', full_name='Messages.Elements.offsets', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='types', full_name='Messages.Elements.types', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ids', full_name='Messages.Elements.ids', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_offsets', full_name='Messages.Elements.id_offsets', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_elements_with_id', full_name='Messages.Elements.num_elements_with_id', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_to_index', full_name='Messages.Elements.id_to_index', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='Messages.Elements.flags', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centers', full_name='Messages.Elements.centers', index=9,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lengths', full_name='Messages.Elements.lengths', index=10,
      number=11, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='areas', full_name='Messages.Elements.areas', index=11,
      number=12, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volumes', full_name='Messages.Elements.volumes', index=12,
      number=13, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=772,
)

_VECTOR32.fields_by_name['revision'].message_type = _REVISION
_VECTOR64.fields_by_name['revision'].message_type = _REVISION
DESCRIPTOR.message_types_by_name['Revision'] = _REVISION
DESCRIPTOR.message_types_by_name['Extrema'] = _EXTREMA
DESCRIPTOR.message_types_by_name['Vector32'] = _VECTOR32
DESCRIPTOR.message_types_by_name['Vector64'] = _VECTOR64
DESCRIPTOR.message_types_by_name['Indices'] = _INDICES
DESCRIPTOR.message_types_by_name['Elements'] = _ELEMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Revision = _reflection.GeneratedProtocolMessageType('Revision', (_message.Message,), {
  'DESCRIPTOR' : _REVISION,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:Messages.Revision)
  })
_sym_db.RegisterMessage(Revision)

Extrema = _reflection.GeneratedProtocolMessageType('Extrema', (_message.Message,), {
  'DESCRIPTOR' : _EXTREMA,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:Messages.Extrema)
  })
_sym_db.RegisterMessage(Extrema)

Vector32 = _reflection.GeneratedProtocolMessageType('Vector32', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR32,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:Messages.Vector32)
  })
_sym_db.RegisterMessage(Vector32)

Vector64 = _reflection.GeneratedProtocolMessageType('Vector64', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR64,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:Messages.Vector64)
  })
_sym_db.RegisterMessage(Vector64)

Indices = _reflection.GeneratedProtocolMessageType('Indices', (_message.Message,), {
  'DESCRIPTOR' : _INDICES,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:Messages.Indices)
  })
_sym_db.RegisterMessage(Indices)

Elements = _reflection.GeneratedProtocolMessageType('Elements', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTS,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:Messages.Elements)
  })
_sym_db.RegisterMessage(Elements)


DESCRIPTOR._options = None
_EXTREMA.fields_by_name['min']._options = None
_EXTREMA.fields_by_name['max']._options = None
_VECTOR32.fields_by_name['values']._options = None
_VECTOR64.fields_by_name['values']._options = None
_INDICES.fields_by_name['values']._options = None
_ELEMENTS.fields_by_name['indices']._options = None
_ELEMENTS.fields_by_name['strides']._options = None
_ELEMENTS.fields_by_name['offsets']._options = None
_ELEMENTS.fields_by_name['types']._options = None
_ELEMENTS.fields_by_name['ids']._options = None
_ELEMENTS.fields_by_name['id_offsets']._options = None
_ELEMENTS.fields_by_name['num_elements_with_id']._options = None
_ELEMENTS.fields_by_name['id_to_index']._options = None
_ELEMENTS.fields_by_name['flags']._options = None
_ELEMENTS.fields_by_name['centers']._options = None
_ELEMENTS.fields_by_name['lengths']._options = None
_ELEMENTS.fields_by_name['areas']._options = None
_ELEMENTS.fields_by_name['volumes']._options = None
# @@protoc_insertion_point(module_scope)
