# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spatial.proto

require 'google/protobuf'

require 'vector_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spatial.proto", :syntax => :proto3) do
    add_message "Messages.Zone" do
      optional :name, :string, 1
      optional :id, :int32, 2
      optional :dimensionality, :int32, 3
      optional :num_elements, :int64, 5
      optional :offset, :int64, 6
      optional :comments, :string, 7
      optional :info, :string, 8
      optional :bounds, :message, 10, "Messages.Extrema"
      repeated :terminal_position, :float, 11
      repeated :specific_elements, :int32, 12
    end
    add_message "Messages.Topology" do
      optional :name, :string, 1
      optional :type, :int32, 2
      optional :ndim, :int32, 3
      optional :basis, :int32, 4
      repeated :resolution, :double, 8
      repeated :data, :message, 9, "Messages.Vector64"
      optional :nodes, :message, 10, "Messages.Elements"
      optional :edges, :message, 11, "Messages.Elements"
      optional :interior_edges, :message, 12, "Messages.Elements"
      optional :faces, :message, 13, "Messages.Elements"
      optional :interior_faces, :message, 14, "Messages.Elements"
      optional :cells, :message, 15, "Messages.Elements"
      repeated :groups, :message, 20, "Messages.Zone"
      repeated :loops, :message, 21, "Messages.Zone"
      repeated :surfaces, :message, 22, "Messages.Zone"
      repeated :volumes, :message, 23, "Messages.Zone"
      repeated :locations, :int32, 26
      optional :filename, :string, 30
      optional :revision, :message, 31, "Messages.Revision"
    end
    add_message "Messages.GridControl" do
      optional :basis, :int32, 1
      repeated :size, :int32, 2
      repeated :spacing, :double, 3
      repeated :grading, :double, 4
      optional :bounds, :message, 10, "Messages.Extrema"
    end
    add_message "Messages.MeshControl" do
      optional :target_n, :int64, 1
      optional :max_iterations, :int32, 2
      optional :size_ratio, :double, 3
      optional :size_decay, :double, 4
      optional :size_exponent, :double, 5
      optional :curv_ratio, :double, 6
      optional :curv_decay, :double, 7
      optional :curv_exponent, :double, 8
      optional :node_radius, :double, 9
      optional :bounds, :message, 10, "Messages.Extrema"
      optional :interior, :bool, 12
      optional :exterior, :bool, 13
      optional :shell, :bool, 14
      optional :equalize, :bool, 15
      optional :smooth, :bool, 16
      optional :include_background, :bool, 18
      optional :keep_existing_points, :bool, 19
      optional :x_symmetry, :bool, 24
      optional :y_symmetry, :bool, 25
      optional :z_symmetry, :bool, 26
      optional :background_n, :int64, 30
    end
    add_message "Messages.TreeControl" do
      optional :min_depth, :int32, 1
      optional :max_depth, :int32, 2
      optional :max_size, :int64, 3
      optional :bounds, :message, 10, "Messages.Extrema"
    end
    add_message "Messages.NetworkControl" do
    end
  end
end

module Messages
  Zone = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Messages.Zone").msgclass
  Topology = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Messages.Topology").msgclass
  GridControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Messages.GridControl").msgclass
  MeshControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Messages.MeshControl").msgclass
  TreeControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Messages.TreeControl").msgclass
  NetworkControl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Messages.NetworkControl").msgclass
end
