<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *compatible with xcompute instruction  (a function instance bound to arguments... data, regions, etc)
 *
 * Generated from protobuf message <code>Messages.Command</code>
 */
class Command extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Messages.Function function = 1;</code>
     */
    protected $function = null;
    /**
     * Generated from protobuf field <code>bool args_are_set = 2;</code>
     */
    protected $args_are_set = false;
    /**
     * Generated from protobuf field <code>bool kernel_ready = 3;</code>
     */
    protected $kernel_ready = false;
    /**
     * Generated from protobuf field <code>int64 exec_count = 4;</code>
     */
    protected $exec_count = 0;
    /**
     * Generated from protobuf field <code>int64 effective_size = 5;</code>
     */
    protected $effective_size = 0;
    /**
     * Generated from protobuf field <code>int64 version = 6;</code>
     */
    protected $version = 0;
    /**
     *unique runtime identifier (assigned and only valid within a server session)
     *
     * Generated from protobuf field <code>int64 id = 7;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 n_kernel = 8;</code>
     */
    protected $n_kernel = 0;
    /**
     * Generated from protobuf field <code>float progress = 9;</code>
     */
    protected $progress = 0.0;
    /**
     * Generated from protobuf field <code>string msg = 10;</code>
     */
    protected $msg = '';
    /**
     *reserved  
     *
     * Generated from protobuf field <code>repeated .Messages.Vector64 data = 12;</code>
     */
    private $data;
    /**
     *optional, to be called from within bound function
     *
     * Generated from protobuf field <code>repeated .Messages.Command before = 13;</code>
     */
    private $before;
    /**
     *optional, to be called from within bound function
     *
     * Generated from protobuf field <code>repeated .Messages.Command after = 14;</code>
     */
    private $after;
    /**
     *if assigned, used to indentify specific zones for conditions, etc
     *
     * Generated from protobuf field <code>repeated int32 region_type = 15;</code>
     */
    private $region_type;
    /**
     *if assigned, used to indentify specific zones for conditions, etc
     *
     * Generated from protobuf field <code>repeated int32 region_id = 16;</code>
     */
    private $region_id;
    /**
     *bound argument type names to operate (name of class or type)
     *
     * Generated from protobuf field <code>repeated string argument_types = 17;</code>
     */
    private $argument_types;
    /**
     *matching argument type descriptions (used by UI)
     *
     * Generated from protobuf field <code>repeated string argument_descriptions = 18;</code>
     */
    private $argument_descriptions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Messages\PBFunction $function
     *     @type bool $args_are_set
     *     @type bool $kernel_ready
     *     @type int|string $exec_count
     *     @type int|string $effective_size
     *     @type int|string $version
     *     @type int|string $id
     *          unique runtime identifier (assigned and only valid within a server session)
     *     @type int|string $n_kernel
     *     @type float $progress
     *     @type string $msg
     *     @type \Messages\Vector64[]|\Google\Protobuf\Internal\RepeatedField $data
     *          reserved  
     *     @type \Messages\Command[]|\Google\Protobuf\Internal\RepeatedField $before
     *          optional, to be called from within bound function
     *     @type \Messages\Command[]|\Google\Protobuf\Internal\RepeatedField $after
     *          optional, to be called from within bound function
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $region_type
     *          if assigned, used to indentify specific zones for conditions, etc
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $region_id
     *          if assigned, used to indentify specific zones for conditions, etc
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $argument_types
     *          bound argument type names to operate (name of class or type)
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $argument_descriptions
     *          matching argument type descriptions (used by UI)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\System::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Messages.Function function = 1;</code>
     * @return \Messages\PBFunction
     */
    public function getFunction()
    {
        return $this->function;
    }

    /**
     * Generated from protobuf field <code>.Messages.Function function = 1;</code>
     * @param \Messages\PBFunction $var
     * @return $this
     */
    public function setFunction($var)
    {
        GPBUtil::checkMessage($var, \Messages\PBFunction::class);
        $this->function = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool args_are_set = 2;</code>
     * @return bool
     */
    public function getArgsAreSet()
    {
        return $this->args_are_set;
    }

    /**
     * Generated from protobuf field <code>bool args_are_set = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setArgsAreSet($var)
    {
        GPBUtil::checkBool($var);
        $this->args_are_set = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool kernel_ready = 3;</code>
     * @return bool
     */
    public function getKernelReady()
    {
        return $this->kernel_ready;
    }

    /**
     * Generated from protobuf field <code>bool kernel_ready = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setKernelReady($var)
    {
        GPBUtil::checkBool($var);
        $this->kernel_ready = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 exec_count = 4;</code>
     * @return int|string
     */
    public function getExecCount()
    {
        return $this->exec_count;
    }

    /**
     * Generated from protobuf field <code>int64 exec_count = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExecCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->exec_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 effective_size = 5;</code>
     * @return int|string
     */
    public function getEffectiveSize()
    {
        return $this->effective_size;
    }

    /**
     * Generated from protobuf field <code>int64 effective_size = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEffectiveSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->effective_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 version = 6;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

    /**
     *unique runtime identifier (assigned and only valid within a server session)
     *
     * Generated from protobuf field <code>int64 id = 7;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *unique runtime identifier (assigned and only valid within a server session)
     *
     * Generated from protobuf field <code>int64 id = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 n_kernel = 8;</code>
     * @return int|string
     */
    public function getNKernel()
    {
        return $this->n_kernel;
    }

    /**
     * Generated from protobuf field <code>int64 n_kernel = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNKernel($var)
    {
        GPBUtil::checkInt64($var);
        $this->n_kernel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float progress = 9;</code>
     * @return float
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     * Generated from protobuf field <code>float progress = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkFloat($var);
        $this->progress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 10;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     *reserved  
     *
     * Generated from protobuf field <code>repeated .Messages.Vector64 data = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *reserved  
     *
     * Generated from protobuf field <code>repeated .Messages.Vector64 data = 12;</code>
     * @param \Messages\Vector64[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Vector64::class);
        $this->data = $arr;

        return $this;
    }

    /**
     *optional, to be called from within bound function
     *
     * Generated from protobuf field <code>repeated .Messages.Command before = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBefore()
    {
        return $this->before;
    }

    /**
     *optional, to be called from within bound function
     *
     * Generated from protobuf field <code>repeated .Messages.Command before = 13;</code>
     * @param \Messages\Command[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBefore($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Command::class);
        $this->before = $arr;

        return $this;
    }

    /**
     *optional, to be called from within bound function
     *
     * Generated from protobuf field <code>repeated .Messages.Command after = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAfter()
    {
        return $this->after;
    }

    /**
     *optional, to be called from within bound function
     *
     * Generated from protobuf field <code>repeated .Messages.Command after = 14;</code>
     * @param \Messages\Command[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAfter($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Command::class);
        $this->after = $arr;

        return $this;
    }

    /**
     *if assigned, used to indentify specific zones for conditions, etc
     *
     * Generated from protobuf field <code>repeated int32 region_type = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegionType()
    {
        return $this->region_type;
    }

    /**
     *if assigned, used to indentify specific zones for conditions, etc
     *
     * Generated from protobuf field <code>repeated int32 region_type = 15;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegionType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->region_type = $arr;

        return $this;
    }

    /**
     *if assigned, used to indentify specific zones for conditions, etc
     *
     * Generated from protobuf field <code>repeated int32 region_id = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegionId()
    {
        return $this->region_id;
    }

    /**
     *if assigned, used to indentify specific zones for conditions, etc
     *
     * Generated from protobuf field <code>repeated int32 region_id = 16;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegionId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->region_id = $arr;

        return $this;
    }

    /**
     *bound argument type names to operate (name of class or type)
     *
     * Generated from protobuf field <code>repeated string argument_types = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgumentTypes()
    {
        return $this->argument_types;
    }

    /**
     *bound argument type names to operate (name of class or type)
     *
     * Generated from protobuf field <code>repeated string argument_types = 17;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgumentTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->argument_types = $arr;

        return $this;
    }

    /**
     *matching argument type descriptions (used by UI)
     *
     * Generated from protobuf field <code>repeated string argument_descriptions = 18;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgumentDescriptions()
    {
        return $this->argument_descriptions;
    }

    /**
     *matching argument type descriptions (used by UI)
     *
     * Generated from protobuf field <code>repeated string argument_descriptions = 18;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgumentDescriptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->argument_descriptions = $arr;

        return $this;
    }

}

