<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *compatible with xcompute model
 *
 * Generated from protobuf message <code>Messages.Model</code>
 */
class Model extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string dofs = 3;</code>
     */
    private $dofs;
    /**
     *ordered algorithms (by name)
     *
     * Generated from protobuf field <code>repeated string algorithms = 4;</code>
     */
    private $algorithms;
    /**
     *serialized property-keys 
     *
     * Generated from protobuf field <code>repeated string available_outputs = 5;</code>
     */
    private $available_outputs;
    /**
     *some pk's are not recorded by default as an optimization. they can be added
     *
     * Generated from protobuf field <code>repeated string extra_properties = 6;</code>
     */
    private $extra_properties;
    /**
     * Generated from protobuf field <code>repeated string compatible_conditions = 7;</code>
     */
    private $compatible_conditions;
    /**
     * Generated from protobuf field <code>repeated string compatible_scripts = 8;</code>
     */
    private $compatible_scripts;
    /**
     *
     * Generated from protobuf field <code>repeated .Messages.Model sub_models = 9;</code>
     */
    private $sub_models;
    /**
     *high-level constants manpulated by user
     *
     * Generated from protobuf field <code>repeated .Messages.Vector64 data = 10;</code>
     */
    private $data;
    /**
     * Generated from protobuf field <code>repeated .Messages.Rule rules = 11;</code>
     */
    private $rules;
    /**
     * Generated from protobuf field <code>repeated .Messages.Rule mutex_stack = 12;</code>
     */
    private $mutex_stack;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $dofs
     *          reserved
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $algorithms
     *          ordered algorithms (by name)
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $available_outputs
     *          serialized property-keys 
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $extra_properties
     *          some pk's are not recorded by default as an optimization. they can be added
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $compatible_conditions
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $compatible_scripts
     *     @type \Messages\Model[]|\Google\Protobuf\Internal\RepeatedField $sub_models
     *     @type \Messages\Vector64[]|\Google\Protobuf\Internal\RepeatedField $data
     *          high-level constants manpulated by user
     *     @type \Messages\Rule[]|\Google\Protobuf\Internal\RepeatedField $rules
     *     @type \Messages\Rule[]|\Google\Protobuf\Internal\RepeatedField $mutex_stack
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\System::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string dofs = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDofs()
    {
        return $this->dofs;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string dofs = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDofs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dofs = $arr;

        return $this;
    }

    /**
     *ordered algorithms (by name)
     *
     * Generated from protobuf field <code>repeated string algorithms = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAlgorithms()
    {
        return $this->algorithms;
    }

    /**
     *ordered algorithms (by name)
     *
     * Generated from protobuf field <code>repeated string algorithms = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAlgorithms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->algorithms = $arr;

        return $this;
    }

    /**
     *serialized property-keys 
     *
     * Generated from protobuf field <code>repeated string available_outputs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAvailableOutputs()
    {
        return $this->available_outputs;
    }

    /**
     *serialized property-keys 
     *
     * Generated from protobuf field <code>repeated string available_outputs = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAvailableOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->available_outputs = $arr;

        return $this;
    }

    /**
     *some pk's are not recorded by default as an optimization. they can be added
     *
     * Generated from protobuf field <code>repeated string extra_properties = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtraProperties()
    {
        return $this->extra_properties;
    }

    /**
     *some pk's are not recorded by default as an optimization. they can be added
     *
     * Generated from protobuf field <code>repeated string extra_properties = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtraProperties($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->extra_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string compatible_conditions = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCompatibleConditions()
    {
        return $this->compatible_conditions;
    }

    /**
     * Generated from protobuf field <code>repeated string compatible_conditions = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCompatibleConditions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->compatible_conditions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string compatible_scripts = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCompatibleScripts()
    {
        return $this->compatible_scripts;
    }

    /**
     * Generated from protobuf field <code>repeated string compatible_scripts = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCompatibleScripts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->compatible_scripts = $arr;

        return $this;
    }

    /**
     *
     * Generated from protobuf field <code>repeated .Messages.Model sub_models = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubModels()
    {
        return $this->sub_models;
    }

    /**
     *
     * Generated from protobuf field <code>repeated .Messages.Model sub_models = 9;</code>
     * @param \Messages\Model[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubModels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Model::class);
        $this->sub_models = $arr;

        return $this;
    }

    /**
     *high-level constants manpulated by user
     *
     * Generated from protobuf field <code>repeated .Messages.Vector64 data = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *high-level constants manpulated by user
     *
     * Generated from protobuf field <code>repeated .Messages.Vector64 data = 10;</code>
     * @param \Messages\Vector64[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Vector64::class);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Messages.Rule rules = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRules()
    {
        return $this->rules;
    }

    /**
     * Generated from protobuf field <code>repeated .Messages.Rule rules = 11;</code>
     * @param \Messages\Rule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Rule::class);
        $this->rules = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Messages.Rule mutex_stack = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMutexStack()
    {
        return $this->mutex_stack;
    }

    /**
     * Generated from protobuf field <code>repeated .Messages.Rule mutex_stack = 12;</code>
     * @param \Messages\Rule[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMutexStack($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Messages\Rule::class);
        $this->mutex_stack = $arr;

        return $this;
    }

}

