<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *compatible with xcompute *.cfg files via machinery defined in config.hpp/config.cpp
 *
 * Generated from protobuf message <code>Messages.Variables</code>
 */
class Variables extends \Google\Protobuf\Internal\Message
{
    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string int_names = 2;</code>
     */
    private $int_names;
    /**
     * Generated from protobuf field <code>repeated int32 int_values = 3;</code>
     */
    private $int_values;
    /**
     * Generated from protobuf field <code>repeated string int_descriptions = 4;</code>
     */
    private $int_descriptions;
    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string bool_names = 6;</code>
     */
    private $bool_names;
    /**
     * Generated from protobuf field <code>repeated bool bool_values = 7;</code>
     */
    private $bool_values;
    /**
     * Generated from protobuf field <code>repeated string bool_descriptions = 8;</code>
     */
    private $bool_descriptions;
    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string double_names = 10;</code>
     */
    private $double_names;
    /**
     * Generated from protobuf field <code>repeated double double_values = 11;</code>
     */
    private $double_values;
    /**
     * Generated from protobuf field <code>repeated string double_descriptions = 12;</code>
     */
    private $double_descriptions;
    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string string_names = 14;</code>
     */
    private $string_names;
    /**
     * Generated from protobuf field <code>repeated string string_values = 15;</code>
     */
    private $string_values;
    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string string_descriptions = 16;</code>
     */
    private $string_descriptions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $int_names
     *          reserved
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $int_values
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $int_descriptions
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $bool_names
     *          reserved
     *     @type bool[]|\Google\Protobuf\Internal\RepeatedField $bool_values
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $bool_descriptions
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $double_names
     *          reserved
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $double_values
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $double_descriptions
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $string_names
     *          reserved
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $string_values
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $string_descriptions
     *          reserved
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\System::initOnce();
        parent::__construct($data);
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string int_names = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntNames()
    {
        return $this->int_names;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string int_names = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->int_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 int_values = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntValues()
    {
        return $this->int_values;
    }

    /**
     * Generated from protobuf field <code>repeated int32 int_values = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->int_values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string int_descriptions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIntDescriptions()
    {
        return $this->int_descriptions;
    }

    /**
     * Generated from protobuf field <code>repeated string int_descriptions = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIntDescriptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->int_descriptions = $arr;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string bool_names = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBoolNames()
    {
        return $this->bool_names;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string bool_names = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBoolNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->bool_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bool bool_values = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBoolValues()
    {
        return $this->bool_values;
    }

    /**
     * Generated from protobuf field <code>repeated bool bool_values = 7;</code>
     * @param bool[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBoolValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->bool_values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string bool_descriptions = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBoolDescriptions()
    {
        return $this->bool_descriptions;
    }

    /**
     * Generated from protobuf field <code>repeated string bool_descriptions = 8;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBoolDescriptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->bool_descriptions = $arr;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string double_names = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDoubleNames()
    {
        return $this->double_names;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string double_names = 10;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDoubleNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->double_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double double_values = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDoubleValues()
    {
        return $this->double_values;
    }

    /**
     * Generated from protobuf field <code>repeated double double_values = 11;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDoubleValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->double_values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string double_descriptions = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDoubleDescriptions()
    {
        return $this->double_descriptions;
    }

    /**
     * Generated from protobuf field <code>repeated string double_descriptions = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDoubleDescriptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->double_descriptions = $arr;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string string_names = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStringNames()
    {
        return $this->string_names;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string string_names = 14;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStringNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->string_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string string_values = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStringValues()
    {
        return $this->string_values;
    }

    /**
     * Generated from protobuf field <code>repeated string string_values = 15;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStringValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->string_values = $arr;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string string_descriptions = 16;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStringDescriptions()
    {
        return $this->string_descriptions;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated string string_descriptions = 16;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStringDescriptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->string_descriptions = $arr;

        return $this;
    }

}

