<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Messages.Visual</code>
 */
class Visual extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Messages.Zone region = 1;</code>
     */
    private $region = null;
    /**
     * Generated from protobuf field <code>.Messages.Representation representation = 2;</code>
     */
    private $representation = null;
    /**
     * Generated from protobuf field <code>int32 style = 3;</code>
     */
    private $style = 0;
    /**
     * Generated from protobuf field <code>repeated int32 points = 4;</code>
     */
    private $points;
    /**
     * Generated from protobuf field <code>repeated int32 lines = 5;</code>
     */
    private $lines;
    /**
     * Generated from protobuf field <code>repeated int32 triangles = 6;</code>
     */
    private $triangles;
    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated int32 indices_per_element = 8;</code>
     */
    private $indices_per_element;
    /**
     *only used on composite elements (e.g. QUAD4 represented using triangles)
     *
     * Generated from protobuf field <code>repeated int32 elements_to_indices = 9;</code>
     */
    private $elements_to_indices;
    /**
     *only used on composite elements (e.g. QUAD4 represented using triangles)
     *
     * Generated from protobuf field <code>repeated int32 indices_to_elements = 10;</code>
     */
    private $indices_to_elements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Messages\Zone $region
     *     @type \Messages\Representation $representation
     *     @type int $style
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $points
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $lines
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $triangles
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $indices_per_element
     *          reserved
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $elements_to_indices
     *          only used on composite elements (e.g. QUAD4 represented using triangles)
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $indices_to_elements
     *          only used on composite elements (e.g. QUAD4 represented using triangles)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Meta::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Messages.Zone region = 1;</code>
     * @return \Messages\Zone
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>.Messages.Zone region = 1;</code>
     * @param \Messages\Zone $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkMessage($var, \Messages\Zone::class);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Messages.Representation representation = 2;</code>
     * @return \Messages\Representation
     */
    public function getRepresentation()
    {
        return $this->representation;
    }

    /**
     * Generated from protobuf field <code>.Messages.Representation representation = 2;</code>
     * @param \Messages\Representation $var
     * @return $this
     */
    public function setRepresentation($var)
    {
        GPBUtil::checkMessage($var, \Messages\Representation::class);
        $this->representation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 style = 3;</code>
     * @return int
     */
    public function getStyle()
    {
        return $this->style;
    }

    /**
     * Generated from protobuf field <code>int32 style = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStyle($var)
    {
        GPBUtil::checkInt32($var);
        $this->style = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 points = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Generated from protobuf field <code>repeated int32 points = 4;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->points = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 lines = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLines()
    {
        return $this->lines;
    }

    /**
     * Generated from protobuf field <code>repeated int32 lines = 5;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLines($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->lines = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 triangles = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTriangles()
    {
        return $this->triangles;
    }

    /**
     * Generated from protobuf field <code>repeated int32 triangles = 6;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTriangles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->triangles = $arr;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated int32 indices_per_element = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndicesPerElement()
    {
        return $this->indices_per_element;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>repeated int32 indices_per_element = 8;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndicesPerElement($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->indices_per_element = $arr;

        return $this;
    }

    /**
     *only used on composite elements (e.g. QUAD4 represented using triangles)
     *
     * Generated from protobuf field <code>repeated int32 elements_to_indices = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElementsToIndices()
    {
        return $this->elements_to_indices;
    }

    /**
     *only used on composite elements (e.g. QUAD4 represented using triangles)
     *
     * Generated from protobuf field <code>repeated int32 elements_to_indices = 9;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElementsToIndices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->elements_to_indices = $arr;

        return $this;
    }

    /**
     *only used on composite elements (e.g. QUAD4 represented using triangles)
     *
     * Generated from protobuf field <code>repeated int32 indices_to_elements = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndicesToElements()
    {
        return $this->indices_to_elements;
    }

    /**
     *only used on composite elements (e.g. QUAD4 represented using triangles)
     *
     * Generated from protobuf field <code>repeated int32 indices_to_elements = 10;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndicesToElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->indices_to_elements = $arr;

        return $this;
    }

}

