<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spatial.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *compatible with xcompute Region
 *
 * Generated from protobuf message <code>Messages.Zone</code>
 */
class Zone extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>int32 dimensionality = 3;</code>
     */
    private $dimensionality = 0;
    /**
     *reserved
     *
     * Generated from protobuf field <code>int64 num_elements = 5;</code>
     */
    private $num_elements = 0;
    /**
     * Generated from protobuf field <code>int64 offset = 6;</code>
     */
    private $offset = 0;
    /**
     * Generated from protobuf field <code>string comments = 7;</code>
     */
    private $comments = '';
    /**
     * Generated from protobuf field <code>string info = 8;</code>
     */
    private $info = '';
    /**
     *reserved
     *
     * Generated from protobuf field <code>.Messages.Extrema bounds = 10;</code>
     */
    private $bounds = null;
    /**
     * Generated from protobuf field <code>repeated float terminal_position = 11;</code>
     */
    private $terminal_position;
    /**
     *optional (if used, ignore offset)
     *
     * Generated from protobuf field <code>repeated int32 specific_elements = 12;</code>
     */
    private $specific_elements;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $id
     *     @type int $dimensionality
     *     @type int|string $num_elements
     *          reserved
     *     @type int|string $offset
     *     @type string $comments
     *     @type string $info
     *     @type \Messages\Extrema $bounds
     *          reserved
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $terminal_position
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $specific_elements
     *          optional (if used, ignore offset)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Spatial::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 dimensionality = 3;</code>
     * @return int
     */
    public function getDimensionality()
    {
        return $this->dimensionality;
    }

    /**
     * Generated from protobuf field <code>int32 dimensionality = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDimensionality($var)
    {
        GPBUtil::checkInt32($var);
        $this->dimensionality = $var;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>int64 num_elements = 5;</code>
     * @return int|string
     */
    public function getNumElements()
    {
        return $this->num_elements;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>int64 num_elements = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumElements($var)
    {
        GPBUtil::checkInt64($var);
        $this->num_elements = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 offset = 6;</code>
     * @return int|string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>int64 offset = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt64($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comments = 7;</code>
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * Generated from protobuf field <code>string comments = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setComments($var)
    {
        GPBUtil::checkString($var, True);
        $this->comments = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string info = 8;</code>
     * @return string
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>string info = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;

        return $this;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>.Messages.Extrema bounds = 10;</code>
     * @return \Messages\Extrema
     */
    public function getBounds()
    {
        return $this->bounds;
    }

    /**
     *reserved
     *
     * Generated from protobuf field <code>.Messages.Extrema bounds = 10;</code>
     * @param \Messages\Extrema $var
     * @return $this
     */
    public function setBounds($var)
    {
        GPBUtil::checkMessage($var, \Messages\Extrema::class);
        $this->bounds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float terminal_position = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTerminalPosition()
    {
        return $this->terminal_position;
    }

    /**
     * Generated from protobuf field <code>repeated float terminal_position = 11;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTerminalPosition($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->terminal_position = $arr;

        return $this;
    }

    /**
     *optional (if used, ignore offset)
     *
     * Generated from protobuf field <code>repeated int32 specific_elements = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpecificElements()
    {
        return $this->specific_elements;
    }

    /**
     *optional (if used, ignore offset)
     *
     * Generated from protobuf field <code>repeated int32 specific_elements = 12;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpecificElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->specific_elements = $arr;

        return $this;
    }

}

